### ISSUE TITLE
No need for "six" library in requirements.txt

### ISSUE THREAD

**Issue by paddyhoran** [MetLife/SSLChecker#17]
Looks like you are all-in on Python 3 (type hints in main).  I don't think you need six to be installed anymore.

**Comment by gattjoe** [comment]
Unfortunately, the [validators](https://github.com/kvesteri/validators/blob/master/setup.py) library requires six>=1.4.0.

**Comment by paddyhoran** [comment]
If it's not a direct dependency though you don't need it in your requirements.txt I don't think...

**Comment by gattjoe** [comment]
fair point, you are right on that one
