### ISSUE TITLE
Consider adopting "black" for the project

### ISSUE THREAD

**Issue by paddyhoran** [MetLife/SSLChecker#18]
https://black.readthedocs.io/en/stable/

**Comment by paddyhoran** [comment]
@gattjoe let me know if want a PR for this, otherwise feel free to close

**Comment by gattjoe** [comment]
I am going to look into it this weekend, looks interesting. I will probably refactor some code next week and use it. Leave it open or do a PR.

**Comment by gattjoe** [comment]
Only thing I noticed so far with black is that it can butcher an "f-string" that is separated across two lines.

**Comment by paddyhoran** [comment]
I don't love all the choices they make but over time I've found it better to have a standard, even if it's not perfect.

You can't change much but I have these options in my `pyproject.toml`:

```
[tool.black]
line-length = 120
skip-string-normalization = true
```

I can't get used to double quoting strings even though I do when using other languages...
